// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKniLSwBL7SVH3H3CuXWE-OaCNgU0ACi4',
    appId: '1:1085304271669:web:e0fd03dde3bae69c14927c',
    messagingSenderId: '1085304271669',
    projectId: 'finalyearproject-cd51e',
    authDomain: 'finalyearproject-cd51e.firebaseapp.com',
    storageBucket: 'finalyearproject-cd51e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbYfXrZiCCXhMkh1jUn72yG22NEx9U1E',
    appId: '1:1085304271669:android:31255189d4aa38aa14927c',
    messagingSenderId: '1085304271669',
    projectId: 'finalyearproject-cd51e',
    storageBucket: 'finalyearproject-cd51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSIc1c9Me_PRFAzVuRRnbuur-EyJopI4',
    appId: '1:1085304271669:ios:90c7235c04efaec214927c',
    messagingSenderId: '1085304271669',
    projectId: 'finalyearproject-cd51e',
    storageBucket: 'finalyearproject-cd51e.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSIc1c9Me_PRFAzVuRRnbuur-EyJopI4',
    appId: '1:1085304271669:ios:2f898295dc09793914927c',
    messagingSenderId: '1085304271669',
    projectId: 'finalyearproject-cd51e',
    storageBucket: 'finalyearproject-cd51e.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
